language: node_js
cache:
  directories:
    - "node_modules" # This will tell Travis CI to cache the dependencies
before_install:
  - yarn global add greenkeeper-lockfile@1 --no-save
  - export PATH=$PATH:`yarn global bin`
before_script:
  - greenkeeper-lockfile-update
script:
  - yarn test
after_script:
  - greenkeeper-lockfile-upload
